name: 'Dotnet Affected'
description: 'Runs dotnet-affected'
author: 'Leonardo Chaia (me@leonardochaia.com)'
branding:
  icon: 'layers'  
  color: 'green'
inputs:
  toolVersion:
    description: 'dotnet-affected version to install'
  from:
    description: 'Commit/branch/revision for git diff'
  to:
    description: 'Commit/branch/revision for git diff'
outputs:
  affected:
    description: The list of changed and affected projects, if any
runs:
  using: 'node16'
  main: 'dist/index.js'
