name: 'Dotnet Affected'
description: 'Runs dotnet-affected'
author: 'Leonardo Chaia (me@leonardochaia.com)'
inputs:
  toolVersion: # change this
    required: false
    description: 'dotnet-affected version to install'
runs:
  using: 'node16'
  main: 'dist/index.js'
